### ISSUE TITLE
what is the version of the package torchtext?

### ISSUE THREAD

**Issue by liudonglei** [tunz/transformer-pytorch#1]
I use torchtext of version 0.2.3 and get this issue:

File "/home/dm/ldl/transformer-pytorch/dataset/translation.py", line 173, in prepare
    pad_token=pad, lower=True, eos_token='<eos>')
TypeError: __init__() got an unexpected keyword argument 'is_target'

maybe the different version cause it.

**Comment by tunz** [comment]
Thanks for the report! I'm using torchtext 0.3.1. I updated the version in requirements.txt.

**Comment by liudonglei** [comment]
thanks for the information.
